services:
  app:
    build:
      context: ./
      dockerfile: dev.Containerfile
    image: apparaatti_dev
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - PORT=8000
    volumes:
      - ./:/opt/app-root/src
    ports:
      - 3000:3000
      - 8000:8000
    container_name: apparaatti_dev
    networks:
      - localhost-network
 # updater:
  #   build:
  #     context: ./
  #     dockerfile: dev.Containerfile
  #   image: apparaatti_dev
  #   environment:
  #     - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
  #     - PORT=4004
  #     - UPDATER_ENABLED=true
  #   volumes:
  #     - ./:/opt/app-root/src
  #   ports:
  #     - 4004:4004
  #   container_name: apparaatti_dev_updater


  db:
    image: docker.io/postgres:15.8-alpine
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    volumes:
      - pg_data:/data
    container_name: apparaatti_db
    networks:
        - localhost-network
    
  redis:
    image: redis:7-alpine
    container_name: apparaatti_redis
    networks:
        - localhost-network

  cypress:
    build:
      context: ./
      dockerfile: cypress.Containerfile
    image: apparaatti_cypress
    depends_on:
      - app
    working_dir: /e2e
    volumes:
      - ./:/e2e
    environment:
      - CYPRESS_baseUrl=http://app:3000
    networks:
      - localhost-network
    # extra_hosts:
      # - "host.docker.internal:host-gateway"
    # networks:
      # - localhost-network
      
    # command: ./scripts/run-cypress.sh

networks:
  localhost-network:
    driver: bridge

volumes:
  pg_data:
