services:
  app:
    build:
      context: ./
      dockerfile: dev.Containerfile
    image: apparaatti_dev
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - PORT=8000
    volumes:
      - ./:/opt/app-root/src
    ports:
      - 3000:3000
      - 8000:8000
    container_name: apparaatti_dev

  db:
    image: docker.io/postgres:15.8-alpine
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    volumes:
      - pg_data:/data
    container_name: apparaatti_db

  redis:
    image: redis:7-alpine
    container_name: apparaatti_redis

volumes:
  pg_data:
